// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtmX8FKC49qkdX68HM_l--c_kS882-fDg',
    appId: '1:541342560029:web:9c5aadb6bb3addc5e17bf4',
    messagingSenderId: '541342560029',
    projectId: 'bloc-2388b',
    authDomain: 'bloc-2388b.firebaseapp.com',
    storageBucket: 'bloc-2388b.appspot.com',
    measurementId: 'G-CRT3FF71EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkpQaIb31HCe1NWu6psoHtAJPiBmAi_HQ',
    appId: '1:541342560029:android:c8d72333cd4e5a17e17bf4',
    messagingSenderId: '541342560029',
    projectId: 'bloc-2388b',
    storageBucket: 'bloc-2388b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLM0GT_9wnnJOBBUtcoOkpxHKzCTmZPNw',
    appId: '1:541342560029:ios:57c611eca6aafc09e17bf4',
    messagingSenderId: '541342560029',
    projectId: 'bloc-2388b',
    storageBucket: 'bloc-2388b.appspot.com',
    iosBundleId: 'com.example.msbTask3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLM0GT_9wnnJOBBUtcoOkpxHKzCTmZPNw',
    appId: '1:541342560029:ios:57c611eca6aafc09e17bf4',
    messagingSenderId: '541342560029',
    projectId: 'bloc-2388b',
    storageBucket: 'bloc-2388b.appspot.com',
    iosBundleId: 'com.example.msbTask3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtmX8FKC49qkdX68HM_l--c_kS882-fDg',
    appId: '1:541342560029:web:c9003d9c9377bc6be17bf4',
    messagingSenderId: '541342560029',
    projectId: 'bloc-2388b',
    authDomain: 'bloc-2388b.firebaseapp.com',
    storageBucket: 'bloc-2388b.appspot.com',
    measurementId: 'G-LFPK1EM8DK',
  );

}